set JAVA_HOME="C:\Program Files\Java\jdk1.5.0_06"
set CATALINA_LIB="C:\Program Files\Apache Software Foundation\Tomcat 5.5\common\lib"
set WIKI_LIB="C:\Program Files\Apache Software Foundation\Tomcat 5.5\webapps\wiki\WEB-INF\lib"
set WIKI_CLASSES="C:\Program Files\Apache Software Foundation\Tomcat 5.5\webapps\wiki\WEB-INF\classes"
set BATCH_UTIL=com.corendal.netapps.framework.core.utils.BatchUtil
set JAVA_OPTS="-XX:+DisableExplicitGC -Xms256m -Xmx256m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC"
set CATALINA_OPTS="-XX:MaxPermSize=128m"
set JAVA_BATCH_1=com.corendal.netapps.framework.core.batches.SendMailBatch
set XML_DB_CONFIG_FILE=confeveryminute.xml
set WIKI_APP_HOME=C:\Program Files\Apache Software Foundation\Tomcat 5.5\webapps\wiki
set CLASSPATH=%CATALINA_LIB%\commons-el.jar;%CATALINA_LIB%\jasper-compiler.jar;%CATALINA_LIB%\jasper-compiler-jdt.jar;%CATALINA_LIB%\jasper-runtime.jar;%CATALINA_LIB%\jsp-api.jar;%CATALINA_LIB%\naming-factory-dbcp.jar;%CATALINA_LIB%\naming-factory.jar;%CATALINA_LIB%\naming-resources.jar;%CATALINA_LIB%\servlet-api.jar;%DIRECTORY_CLASSES%;%DIRECTORY_LIB%\activation.jar;%DIRECTORY_LIB%\antlr.jar;%DIRECTORY_LIB%\asm-attrs.jar;%DIRECTORY_LIB%\asm.jar;%DIRECTORY_LIB%\axis-ant.jar;%DIRECTORY_LIB%\axis-wsse-1.0.jar;%DIRECTORY_LIB%\axis.jar;%DIRECTORY_LIB%\c3p0-0.9.1-pre11.jar;%DIRECTORY_LIB%\c3p0-oracle-thin-extras-0.9.1-pre11.jar;%DIRECTORY_LIB%\cglib-2.1.jar;%DIRECTORY_LIB%\commons-codec-1.2.jar;%DIRECTORY_LIB%\commons-collections-2.1.1.jar;%DIRECTORY_LIB%\commons-discovery-0.2.jar;%DIRECTORY_LIB%\commons-lang-2.4.jar;%DIRECTORY_LIB%\commons-logging-1.0.4.jar;%DIRECTORY_LIB%\commons-pool-1.1.jar;%DIRECTORY_LIB%\dom3-xercesImpl.jar;%DIRECTORY_LIB%\dom3-xml-apis.jar;%DIRECTORY_LIB%\dom4j-1.6.jar;%DIRECTORY_LIB%\ehcache-1.1.jar;%DIRECTORY_LIB%\excalibur-cli-1.0.jar;%DIRECTORY_LIB%\exist.jar;%DIRECTORY_LIB%\framework.jar;%DIRECTORY_LIB%\hibernate3.jar;%DIRECTORY_LIB%\imap.jar;%DIRECTORY_LIB%\jakarta-bcel-20040329.jar;%DIRECTORY_LIB%\jakarta-regexp-1.3.jar;%DIRECTORY_LIB%\jaxrpc.jar;%DIRECTORY_LIB%\jcifs-1.2.10.jar;%DIRECTORY_LIB%\jdbc2_0-stdext.jar;%DIRECTORY_LIB%\jta.jar;%DIRECTORY_LIB%\libreadline-java.jar;%DIRECTORY_LIB%\log4j-1.2.14.jar;%DIRECTORY_LIB%\mailapi.jar;%DIRECTORY_LIB%\mysql-connector-java-3.0.15-ga-bin.jar;%DIRECTORY_LIB%\ojdbc14.jar;%DIRECTORY_LIB%\pop3.jar;%DIRECTORY_LIB%\portlet.jar;%DIRECTORY_LIB%\saaj.jar;%DIRECTORY_LIB%\smtp.jar;%DIRECTORY_LIB%\jtds-1.2.jar;%DIRECTORY_LIB%\velocity-1.4.jar;%DIRECTORY_LIB%\velocity-dep-1.4.jar;%DIRECTORY_LIB%\wsdl4j-1.5.1.jar;%DIRECTORY_LIB%\xalan-2.7.0.jar;%DIRECTORY_LIB%\xindice-1.1b4.jar;%DIRECTORY_LIB%\xml-apis.jar;%DIRECTORY_LIB%\xml-commons-resolver-CVS-20050605.jar;%DIRECTORY_LIB%\xmldb.jar;%DIRECTORY_LIB%\xmlrpc-1.2-patched.jar
%JAVA_HOME%\bin\java -classpath %CLASSPATH% %BATCH_UTIL% %JAVA_BATCH_1% "-webapppath=%WIKI_APP_HOME%" "-xmldbconfigfile=%XML_DB_CONFIG_FILE%"
